# Generated by Django 4.0.5 on 2022-07-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ano', models.IntegerField()),
                ('Semana', models.IntegerField()),
                ('Secao', models.CharField(max_length=300)),
                ('Produto', models.IntegerField()),
                ('Descricao', models.CharField(max_length=300)),
                ('Quantidade', models.IntegerField()),
                ('Faturamento', models.IntegerField()),
                ('Positivacao', models.IntegerField()),
                ('Cobertura', models.IntegerField()),
                ('Regiao', models.IntegerField()),
            ],
        ),
    ]
